export const BADGE_CATEGORIES = {
  'Languages': [
    { label: 'JavaScript', color: 'F7DF1E', logo: 'javascript', logoColor: 'black' },
    { label: 'TypeScript', color: '3178C6', logo: 'typescript', logoColor: 'white' },
    { label: 'Python', color: '3776AB', logo: 'python', logoColor: 'white' },
    { label: 'Rust', color: '000000', logo: 'rust', logoColor: 'white' },
    { label: 'Go', color: '00ADD8', logo: 'go', logoColor: 'white' },
    { label: 'Java', color: 'ED8B00', logo: 'openjdk', logoColor: 'white' },
    { label: 'C++', color: '00599C', logo: 'cplusplus', logoColor: 'white' },
    { label: 'C#', color: '239120', logo: 'csharp', logoColor: 'white' },
    { label: 'PHP', color: '777BB4', logo: 'php', logoColor: 'white' },
    { label: 'Ruby', color: 'CC342D', logo: 'ruby', logoColor: 'white' },
    { label: 'Swift', color: 'FA7343', logo: 'swift', logoColor: 'white' },
    { label: 'Kotlin', color: '7F52FF', logo: 'kotlin', logoColor: 'white' },
    { label: 'Dart', color: '0175C2', logo: 'dart', logoColor: 'white' },
  ],
  'Frameworks': [
    { label: 'React', color: '61DAFB', logo: 'react', logoColor: 'black' },
    { label: 'Next.js', color: '000000', logo: 'nextdotjs', logoColor: 'white' },
    { label: 'Vue.js', color: '4FC08D', logo: 'vuedotjs', logoColor: 'white' },
    { label: 'Angular', color: 'DD0031', logo: 'angular', logoColor: 'white' },
    { label: 'Svelte', color: 'FF3E00', logo: 'svelte', logoColor: 'white' },
    { label: 'Express', color: '000000', logo: 'express', logoColor: 'white' },
    { label: 'FastAPI', color: '009688', logo: 'fastapi', logoColor: 'white' },
    { label: 'Django', color: '092E20', logo: 'django', logoColor: 'white' },
    { label: 'Flask', color: '000000', logo: 'flask', logoColor: 'white' },
    { label: 'Spring', color: '6DB33F', logo: 'spring', logoColor: 'white' },
    { label: 'Flutter', color: '02569B', logo: 'flutter', logoColor: 'white' },
    { label: 'Tailwind CSS', color: '06B6D4', logo: 'tailwindcss', logoColor: 'white' },
    { label: 'Node.js', color: '339933', logo: 'nodedotjs', logoColor: 'white' },
  ],
  'Tools': [
    { label: 'Docker', color: '2496ED', logo: 'docker', logoColor: 'white' },
    { label: 'Kubernetes', color: '326CE5', logo: 'kubernetes', logoColor: 'white' },
    { label: 'Git', color: 'F05032', logo: 'git', logoColor: 'white' },
    { label: 'GitHub', color: '181717', logo: 'github', logoColor: 'white' },
    { label: 'PostgreSQL', color: '4169E1', logo: 'postgresql', logoColor: 'white' },
    { label: 'MongoDB', color: '47A248', logo: 'mongodb', logoColor: 'white' },
    { label: 'Redis', color: 'DC382D', logo: 'redis', logoColor: 'white' },
    { label: 'Nginx', color: '009639', logo: 'nginx', logoColor: 'white' },
    { label: 'Vite', color: '646CFF', logo: 'vite', logoColor: 'white' },
    { label: 'Webpack', color: '8DD6F9', logo: 'webpack', logoColor: 'black' },
    { label: 'AWS', color: '232F3E', logo: 'amazonaws', logoColor: 'white' },
    { label: 'Vercel', color: '000000', logo: 'vercel', logoColor: 'white' },
  ],
  'Status': [
    { label: 'MIT License', color: 'yellow', logo: '', logoColor: '', static: true, message: 'MIT' },
    { label: 'Apache 2.0', color: 'blue', logo: '', logoColor: '', static: true, message: 'Apache 2.0' },
    { label: 'GPL v3', color: 'blue', logo: '', logoColor: '', static: true, message: 'GPL v3' },
    { label: 'PRs Welcome', color: 'brightgreen', logo: '', logoColor: '', static: true, message: 'PRs Welcome', labelText: 'contributions' },
    { label: 'Maintained', color: 'green', logo: '', logoColor: '', static: true, message: 'yes', labelText: 'maintained' },
    { label: 'WIP', color: 'orange', logo: '', logoColor: '', static: true, message: 'WIP', labelText: 'status' },
  ],
  'GitHub': [
    { label: 'Stars',        github: true, path: 'stars',          color: 'yellow', logo: 'github', logoColor: 'white', style: 'social' },
    { label: 'Forks',        github: true, path: 'forks',          color: 'blue',   logo: 'github', logoColor: 'white', style: 'social' },
    { label: 'Watchers',     github: true, path: 'watchers',       color: 'blue',   logo: 'github', logoColor: 'white', style: 'social' },
    { label: 'Issues',       github: true, path: 'issues',         color: 'red',    logo: 'github', logoColor: 'white' },
    { label: 'Open PRs',     github: true, path: 'issues-pr',      color: 'blue',   logo: 'github', logoColor: 'white' },
    { label: 'Last Commit',  github: true, path: 'last-commit',    color: '333',    logo: 'github', logoColor: 'white' },
    { label: 'Contributors', github: true, path: 'contributors',   color: '444',    logo: 'github', logoColor: 'white' },
    { label: 'License',      github: true, path: 'license',        color: 'blue',   logo: 'github', logoColor: 'white' },
    { label: 'Repo Size',    github: true, path: 'repo-size',      color: '555',    logo: 'github', logoColor: 'white' },
    { label: 'Code Size',    github: true, path: 'languages/code-size', color: '555', logo: 'github', logoColor: 'white' },
    { label: 'Top Language', github: true, path: 'languages/top',  color: '555',    logo: 'github', logoColor: 'white' },
  ],
};

